let a = {
  data: {
    best_day: null,
    categories: [],
    created_at: '2020-06-03T02:54:13Z',
    daily_average: 0,
    daily_average_including_other_language: 0,
    days_including_holidays: 7,
    days_minus_holidays: 7,
    dependencies: [],
    editors: [],
    end: '2020-06-02T15:59:59Z',
    holidays: 0,
    human_readable_daily_average: '0 secs',
    human_readable_daily_average_including_other_language: '0 secs',
    human_readable_total: '0 secs',
    human_readable_total_including_other_language: '0 secs',
    id: '88c3c15c-d514-40b6-80e4-996b27bedc5b',
    is_already_updating: false,
    is_coding_activity_visible: true,
    is_including_today: false,
    is_other_usage_visible: true,
    is_stuck: false,
    is_up_to_date: true,
    languages: [],
    machines: [],
    modified_at: '2020-06-03T02:54:13Z',
    operating_systems: [],
    project: null,
    projects: [],
    range: 'last_7_days',
    start: '2020-05-26T16:00:00Z',
    status: 'ok',
    timeout: 15,
    timezone: 'Asia/Shanghai',
    total_seconds: 0,
    total_seconds_including_other_language: 0,
    user_id: 'f7814922-b859-4566-8715-9ac17f7e0f93',
    username: 'SY',
    writes_only: false
  }
}